# Generated by Django 4.0.1 on 2022-01-29 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تخصص')),
                ('cost', models.IntegerField(verbose_name='هزینه')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='لینک کوتاه')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childern', to='visit.specialization', verbose_name='تخصص')),
            ],
        ),
        migrations.CreateModel(
            name='VisitTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('status', models.CharField(choices=[('created', 'created'), ('reserved', 'reserved'), ('canseled', 'canceld'), ('done', 'done')], default='created', max_length=20)),
                ('count', models.IntegerField(verbose_name='count')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.profiledoctor')),
                ('sick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.profilesick')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.specialization')),
            ],
        ),
    ]
