# Generated by Django 4.0.1 on 2022-01-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visittime',
            name='sick',
        ),
    ]
