# Generated by Django 4.0.1 on 2022-01-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_initial'),
        ('visit', '0002_remove_visittime_sick'),
    ]

    operations = [
        migrations.AddField(
            model_name='visittime',
            name='sick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acc.profilesick'),
        ),
    ]
