# Generated by Django 4.0.1 on 2022-01-31 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_alter_profilesick_cash'),
        ('visit', '0003_visittime_sick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(verbose_name='مبلغ شارژ حساب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acc.profilesick')),
            ],
        ),
    ]
