# Generated by Django 4.0.1 on 2022-01-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_profilesick_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesick',
            name='cash',
            field=models.IntegerField(blank=True, default=0, verbose_name='موجودی'),
        ),
    ]
